on:
  push:
    branches:
    - master
env:
  DOTNET_CORE_VERSION: 7.0.x
  CONTAINER_APP_NAME: rouriewebapi-container-app
  CONTAINER_APP_ENVIRONMENT_NAME: managedEnvContainer
  RESOURCE_GROUP: MSCourseRG
  CONTAINER_REGISTRY_NAME: registrydnsprefix
  CONTAINER_REGISTRY_LOGIN_SERVER: registrydnsprefix.azurecr.io
jobs:
  BuildAndDeployContainerApp:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    - name: Azure login
      uses: azure/login@v1
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}


    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
          azcliversion: latest
          inlineScript: |
            az account show
    - name: Container App deploy
      uses: azure/container-apps-deploy-action@v1
      with:
        appSourcePath: ${{ github.workspace }}
        acrName: ${{ env.CONTAINER_REGISTRY_NAME }}
        acrUsername: ${{ secrets.registrydnsprefix_USERNAME_97DE }}
        acrPassword: ${{ secrets.registrydnsprefix_PASSWORD_97DE }}
        imageToBuild: ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ env.CONTAINER_APP_NAME }}:${{ github.sha }}
        containerAppName: ${{ env.CONTAINER_APP_NAME }}
        containerAppEnvironment: ${{ env.CONTAINER_APP_ENVIRONMENT_NAME }}
        resourceGroup: ${{ env.RESOURCE_GROUP }}
